# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgED5HqKyeZ4U8-p520qvi4JEWqac5Yk
"""

!pip install kaggle --quiet

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score, roc_curve)
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, WeightedRandomSampler

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)

print("✅ All imports done")
print(f"PyTorch version: {torch.__version__}")

!pip install kagglehub --quiet

import kagglehub
import glob
import os

path = kagglehub.dataset_download("ankushpanday1/pcos-prediction-datasettop-75-countries")
print("✅ Path to dataset files:", path)

csv_files = glob.glob(os.path.join(path, "**/*.csv"), recursive=True)
print(f"\n📁 CSV files found: {csv_files}")

csv_files = glob.glob(os.path.join(path, "**/*.csv"), recursive=True)
df = pd.read_csv(csv_files[0])

import glob
csv_files = glob.glob("*.csv")
df = pd.read_csv(csv_files[0])

print("=" * 60)
print(f"📊 Dataset Shape: {df.shape}")
print(f"   Rows: {df.shape[0]} | Columns: {df.shape[1]}")
print("=" * 60)

print("\n📋 Column Names:")
for i, col in enumerate(df.columns):
    print(f"  {i+1:3}. {col}")

print("\n🔍 Data Types:")
print(df.dtypes.value_counts())

print("\n📌 First 3 rows:")
df.head(3)

possible_targets = ['PCOS', 'pcos', 'PCOS_diagnosis', 'diagnosis',
                    'target', 'label', 'PCOS (Y/N)', 'pcos_diagnosis']

TARGET_COL = None
for col in df.columns:
    if col.strip().lower().replace(" ", "_") in [t.lower() for t in possible_targets]:
        TARGET_COL = col
        break

if TARGET_COL is None:
    print("⚠️  Could not auto-detect target. Printing all columns to help you pick:")
    print(df.columns.tolist())
    TARGET_COL = input("Enter target column name exactly: ").strip()

print(f"\n✅ Target Column: '{TARGET_COL}'")

print("\n📊 Class Distribution:")
vc = df[TARGET_COL].value_counts()
print(vc)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

vc.plot(kind='bar', ax=axes[0], color=['#4CAF50', '#F44336'], edgecolor='black')
axes[0].set_title('Class Distribution (Count)', fontsize=13, fontweight='bold')
axes[0].set_xlabel('PCOS Diagnosis')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=0)
for bar, val in zip(axes[0].patches, vc.values):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                 str(val), ha='center', fontweight='bold')

axes[1].pie(vc.values, labels=vc.index, autopct='%1.1f%%',
            colors=['#4CAF50', '#F44336'], startangle=90,
            wedgeprops={'edgecolor': 'white', 'linewidth': 2})
axes[1].set_title('Class Distribution (%)', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.show()

print("\n🔍 Missing Values:")
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'Count': missing, 'Percentage': missing_pct})
missing_df = missing_df[missing_df['Count'] > 0].sort_values('Percentage', ascending=False)

if len(missing_df) == 0:
    print("  ✅ No missing values found!")
else:
    print(missing_df)
    plt.figure(figsize=(10, 4))
    missing_df['Percentage'].plot(kind='bar', color='#FF7043', edgecolor='black')
    plt.title('Missing Values by Column (%)', fontsize=13, fontweight='bold')
    plt.ylabel('Missing %')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()

if TARGET_COL in numeric_cols:
    numeric_cols.remove(TARGET_COL)
if TARGET_COL in cat_cols:
    cat_cols.remove(TARGET_COL)

print(f"🔢 Numeric features  : {len(numeric_cols)}")
print(f"🔤 Categorical features: {len(cat_cols)}")

if len(numeric_cols) > 0:
    n = len(numeric_cols)
    cols_per_row = 4
    rows = (n + cols_per_row - 1) // cols_per_row

    fig, axes = plt.subplots(rows, cols_per_row,
                              figsize=(cols_per_row * 4, rows * 3))
    axes = axes.flatten() if rows > 1 else [axes] if cols_per_row == 1 else axes.flatten()

    for i, col in enumerate(numeric_cols):
        ax = axes[i]
        df[col].dropna().hist(ax=ax, bins=30, color='#42A5F5',
                               edgecolor='white', alpha=0.85)
        ax.set_title(col, fontsize=9, fontweight='bold')
        ax.set_xlabel('')
        ax.tick_params(labelsize=7)

    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)

    plt.suptitle('Numeric Feature Distributions', fontsize=14,
                 fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.show()
if len(numeric_cols) >= 2:
    plt.figure(figsize=(min(16, len(numeric_cols)), min(12, len(numeric_cols) - 1)))
    corr = df[numeric_cols].corr()
    mask = np.triu(np.ones_like(corr, dtype=bool))
    sns.heatmap(corr, mask=mask, annot=len(numeric_cols) <= 15,
                fmt='.2f', cmap='coolwarm', center=0,
                linewidths=0.5, square=True, annot_kws={'size': 7})
    plt.title('Feature Correlation Matrix', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()

if len(cat_cols) > 0:
    print(f"\n📊 Categorical Feature Value Counts:")
    for col in cat_cols[:10]:
        print(f"\n  {col}:")
        print(df[col].value_counts().to_string(index=True))

df_clean = df.copy()

id_like_cols = [col for col in df_clean.columns
                if col.lower() in ['id', 'patient_id', 'sl. no', 'sl.no', 'index']
                or (df_clean[col].dtype == object and
                    df_clean[col].nunique() / len(df_clean) > 0.95)]

if id_like_cols:
    print(f"🗑️  Dropping ID-like columns: {id_like_cols}")
    df_clean.drop(columns=id_like_cols, inplace=True)

le_target = LabelEncoder()
if df_clean[TARGET_COL].dtype == object:
    df_clean[TARGET_COL] = le_target.fit_transform(df_clean[TARGET_COL])
    print(f"\n✅ Target encoded: {dict(zip(le_target.classes_, le_target.transform(le_target.classes_)))}")
else:
    unique_vals = df_clean[TARGET_COL].unique()
    if set(unique_vals) != {0, 1}:
        df_clean[TARGET_COL] = (df_clean[TARGET_COL] == unique_vals.max()).astype(int)
    print(f"\n✅ Target is numeric. Classes: {sorted(df_clean[TARGET_COL].unique())}")

num_cols = df_clean.select_dtypes(include=[np.number]).columns.tolist()
cat_cols_clean = df_clean.select_dtypes(include=['object']).columns.tolist()

if TARGET_COL in num_cols:
    num_cols.remove(TARGET_COL)
if TARGET_COL in cat_cols_clean:
    cat_cols_clean.remove(TARGET_COL)

for col in num_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].median(), inplace=True)

for col in cat_cols_clean:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

print(f"\n✅ Missing values after imputation: {df_clean.isnull().sum().sum()}")

le_encoders = {}
for col in cat_cols_clean:
    le = LabelEncoder()
    df_clean[col] = le.fit_transform(df_clean[col].astype(str))
    le_encoders[col] = le

if cat_cols_clean:
    print(f"✅ Label encoded {len(cat_cols_clean)} categorical columns")

def cap_outliers_iqr(df, cols, factor=3.0):
    """Cap outliers using IQR method."""
    df = df.copy()
    for col in cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - factor * IQR
        upper = Q3 + factor * IQR
        df[col] = df[col].clip(lower=lower, upper=upper)
    return df

feature_cols = [c for c in df_clean.columns if c != TARGET_COL]
df_clean = cap_outliers_iqr(df_clean, num_cols, factor=3.0)
print("✅ Outliers capped (IQR × 3.0)")

X = df_clean[feature_cols].values.astype(np.float32)
y = df_clean[TARGET_COL].values.astype(np.float32)

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=SEED, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=SEED, stratify=y_temp)

print(f"\n📦 Split Summary:")
print(f"  Train : {X_train.shape[0]} samples ({X_train.shape[0]/len(X)*100:.1f}%)")
print(f"  Val   : {X_val.shape[0]} samples  ({X_val.shape[0]/len(X)*100:.1f}%)")
print(f"  Test  : {X_test.shape[0]} samples  ({X_test.shape[0]/len(X)*100:.1f}%)")

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)
print("\n✅ Features standardized (fit on train only)")

class PCOSDetector(nn.Module):
    """
    Multi-Layer Perceptron for PCOS Binary Classification.

    Architecture:
        Input → FC(256) → BN → ReLU → Dropout
              → FC(128) → BN → ReLU → Dropout
              → FC(64)  → BN → ReLU → Dropout
              → FC(32)  → BN → ReLU → Dropout
              → FC(1)   → Sigmoid
    """
    def __init__(self, input_dim, hidden_dims=[256, 128, 64, 32],
                 dropout_rate=0.3):
        super(PCOSDetector, self).__init__()

        self.input_dim   = input_dim
        self.hidden_dims = hidden_dims
        self.dropout_rate = dropout_rate

        layers = []
        in_dim = input_dim

        for i, out_dim in enumerate(hidden_dims):
            layers.append(nn.Linear(in_dim, out_dim))
            layers.append(nn.BatchNorm1d(out_dim))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(p=dropout_rate))
            in_dim = out_dim

        layers.append(nn.Linear(in_dim, 1))
        layers.append(nn.Sigmoid())

        self.network = nn.Sequential(*layers)
        self._init_weights()

    def _init_weights(self):
        for layer in self.modules():
            if isinstance(layer, nn.Linear):
                nn.init.kaiming_normal_(layer.weight, nonlinearity='relu')
                nn.init.zeros_(layer.bias)

    def forward(self, x):
        return self.network(x).squeeze(1)

    def count_parameters(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)


INPUT_DIM = X_train.shape[1]
model = PCOSDetector(
    input_dim    = INPUT_DIM,
    hidden_dims  = [256, 128, 64, 32],
    dropout_rate = 0.3
)

print("=" * 55)
print("🧠 PCOS Detector — MLP Architecture")
print("=" * 55)
print(model)
print("=" * 55)
print(f"📐 Input Features     : {INPUT_DIM}")
print(f"⚙️  Total Parameters  : {model.count_parameters():,}")
print("=" * 55)

DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 32

print(f"🖥️  Device: {DEVICE}")

def to_tensors(X, y):
    return (torch.FloatTensor(X).to(DEVICE),
            torch.FloatTensor(y).to(DEVICE))

X_train_t, y_train_t = to_tensors(X_train, y_train)
X_val_t,   y_val_t   = to_tensors(X_val,   y_val)
X_test_t,  y_test_t  = to_tensors(X_test,  y_test)

class_counts = np.bincount(y_train.astype(int))
class_weights_np = 1.0 / class_counts
sample_weights = class_weights_np[y_train.astype(int)]

sampler = WeightedRandomSampler(
    weights     = torch.DoubleTensor(sample_weights),
    num_samples = len(sample_weights),
    replacement = True
)
train_ds = TensorDataset(X_train_t, y_train_t)
val_ds   = TensorDataset(X_val_t,   y_val_t)
test_ds  = TensorDataset(X_test_t,  y_test_t)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE,
                          sampler=sampler)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False)

print(f"\n✅ DataLoaders ready")
print(f"  Train batches : {len(train_loader)}")
print(f"  Val batches   : {len(val_loader)}")
print(f"  Test batches  : {len(test_loader)}")
print(f"\n  Class 0 (No PCOS) : {class_counts[0]} samples")
print(f"  Class 1 (PCOS)    : {class_counts[1]} samples")
print(f"  Imbalance ratio   : {class_counts[0]/class_counts[1]:.2f}:1")
print(f"\n  ✅ WeightedRandomSampler applied to balance training")

model = model.to(DEVICE)
print(f"\n  Model moved to: {DEVICE}")
