# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iv5gJW1NrD_y6HCJdHv1IU7y4qvpQgBc
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from collections import Counter
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from torchvision import transforms
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ All imports done")
print(f"🖥️  Device: {DEVICE}")
print(f"PyTorch version: {torch.__version__}")

!pip install kagglehub --quiet

import kagglehub
import os
from pathlib import Path

path = kagglehub.dataset_download("anaghachoudhari/pcos-detection-using-ultrasound-images")
print("✅ Path to dataset files:", path)

print("\n📁 Dataset folder structure:")
for root, dirs, files_list in os.walk(path):
    level = root.replace(path, "").count(os.sep)
    indent = "  " * level
    print(f"{indent}📂 {os.path.basename(root)}/")
    if level < 3:
        for f in files_list[:3]:
            print(f"{indent}  📄 {f}")

DATA_DIR  = Path(path)

all_subdirs = [d for d in DATA_DIR.rglob("*") if d.is_dir()]
print("📁 All subdirectories found:")
for d in all_subdirs:
    print(f"   {d}")

TRAIN_DIR = None
TEST_DIR  = None

for d in all_subdirs:
    name = d.name.lower()
    if name == "train":
        TRAIN_DIR = d
    elif name == "test":
        TEST_DIR = d

print(f"\n✅ Train Dir : {TRAIN_DIR}")
print(f"✅ Test Dir  : {TEST_DIR}")

CLASS_NAMES = sorted([d.name for d in TRAIN_DIR.iterdir() if d.is_dir()])
print(f"📋 Classes found: {CLASS_NAMES}")

def count_images(split_dir):
    counts = {}
    for cls in CLASS_NAMES:
        cls_path = split_dir / cls
        imgs = list(cls_path.glob("*.jpg")) + \
               list(cls_path.glob("*.png")) + \
               list(cls_path.glob("*.jpeg"))
        counts[cls] = len(imgs)
    return counts

train_counts = count_images(TRAIN_DIR)
test_counts  = count_images(TEST_DIR)

print("\n📊 Image Counts:")
print(f"{'Class':<15} {'Train':>8} {'Test':>8} {'Total':>8}")
print("-" * 35)
for cls in CLASS_NAMES:
    total = train_counts[cls] + test_counts[cls]
    print(f"{cls:<15} {train_counts[cls]:>8} {test_counts[cls]:>8} {total:>8}")
print("-" * 35)
total_train = sum(train_counts.values())
total_test  = sum(test_counts.values())
print(f"{'TOTAL':<15} {total_train:>8} {total_test:>8} {total_train+total_test:>8}")

# ── Class distribution plot ──
colors = ['#EF5350', '#42A5F5']
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for ax, (split_name, counts) in zip(axes,
        [("Train", train_counts), ("Test", test_counts)]):
    bars = ax.bar(counts.keys(), counts.values(),
                  color=colors, edgecolor='black', width=0.5)
    ax.set_title(f'{split_name} Set Distribution',
                 fontsize=13, fontweight='bold')
    ax.set_ylabel('Image Count')
    for bar, val in zip(bars, counts.values()):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 10, str(val),
                ha='center', fontweight='bold', fontsize=11)
    ax.set_ylim(0, max(counts.values()) * 1.2)

plt.suptitle('PCOS Ultrasound Dataset — Class Distribution',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# ── Sample images ──
fig, axes = plt.subplots(2, 5, figsize=(16, 7))
for row, cls in enumerate(CLASS_NAMES):
    cls_path = TRAIN_DIR / cls
    img_paths = list(cls_path.glob("*.jpg")) + \
                list(cls_path.glob("*.png")) + \
                list(cls_path.glob("*.jpeg"))
    sample_paths = np.random.choice(img_paths,
                                    size=min(5, len(img_paths)),
                                    replace=False)
    for col, img_path in enumerate(sample_paths):
        img = Image.open(img_path).convert("RGB")
        axes[row][col].imshow(img, cmap='gray')
        axes[row][col].set_title(
            f"{'PCOS' if cls=='infected' else 'Healthy'}\n{img.size}",
            fontsize=9, fontweight='bold',
            color='#EF5350' if cls == 'infected' else '#42A5F5')
        axes[row][col].axis('off')

plt.suptitle('Sample Ultrasound Images — PCOS vs Healthy',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("🔍 Analyzing image properties (sampling 100 per class)...")

sizes       = []
pixel_means = []
pixel_stds  = []
class_labels_eda = []

for cls in CLASS_NAMES:
    cls_path = TRAIN_DIR / cls
    img_paths = list(cls_path.glob("*.jpg")) + \
                list(cls_path.glob("*.png")) + \
                list(cls_path.glob("*.jpeg"))

    sample = np.random.choice(img_paths, size=min(100, len(img_paths)), replace=False)

    for p in sample:
        img = Image.open(p).convert("RGB")
        arr = np.array(img) / 255.0
        sizes.append(img.size)
        pixel_means.append(arr.mean())
        pixel_stds.append(arr.std())
        class_labels_eda.append(cls)

# Unique sizes
unique_sizes = Counter(sizes)
print(f"\n📐 Unique image sizes (top 5): {unique_sizes.most_common(5)}")

# Pixel stats
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

# Mean pixel intensity by class
for cls, color in zip(CLASS_NAMES, colors):
    vals = [pixel_means[i] for i, l in enumerate(class_labels_eda) if l == cls]
    axes[0].hist(vals, bins=30, alpha=0.7, label=cls, color=color, edgecolor='white')
axes[0].set_title('Pixel Mean Intensity Distribution', fontweight='bold')
axes[0].set_xlabel('Mean Pixel Value')
axes[0].set_ylabel('Count')
axes[0].legend()

# Std by class
for cls, color in zip(CLASS_NAMES, colors):
    vals = [pixel_stds[i] for i, l in enumerate(class_labels_eda) if l == cls]
    axes[1].hist(vals, bins=30, alpha=0.7, label=cls, color=color, edgecolor='white')
axes[1].set_title('Pixel Std Dev Distribution', fontweight='bold')
axes[1].set_xlabel('Std Dev of Pixel Values')
axes[1].set_ylabel('Count')
axes[1].legend()

plt.suptitle('Image Pixel Statistics by Class', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

all_means = np.array(pixel_means)
all_stds  = np.array(pixel_stds)
print(f"\n📊 Dataset Normalization Stats (from samples):")
print(f"  Mean : {all_means.mean():.4f}")
print(f"  Std  : {all_stds.mean():.4f}")

NORM_MEAN = [all_means.mean()] * 3
NORM_STD  = [all_stds.mean()] * 3
print(f"\n  ✅ Will use for normalization:")
print(f"     mean={[round(m,4) for m in NORM_MEAN]}")
print(f"     std ={[round(s,4) for s in NORM_STD]}")

IMG_SIZE = 128   # Resize to 128×128 (good balance of detail vs speed)

# ── Transforms ──
train_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.2),
    transforms.RandomRotation(degrees=15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.RandomAffine(degrees=0, translate=(0.05, 0.05)),
    transforms.ToTensor(),
    transforms.Normalize(mean=NORM_MEAN, std=NORM_STD)
])

val_test_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=NORM_MEAN, std=NORM_STD)
])

# ── Custom Dataset Class ──
class PCOSImageDataset(Dataset):
    """
    Custom PyTorch Dataset for PCOS Ultrasound Images.
    Expects folder structure: root_dir/class_name/image.jpg
    Labels: infected=1 (PCOS), notinfected=0 (Healthy)
    """
    def __init__(self, root_dir, class_names, transform=None):
        self.root_dir    = Path(root_dir)
        self.class_names = class_names
        self.transform   = transform

        # class → label mapping
        # infected=1, notinfected=0
        self.class_to_idx = {
            cls: (1 if 'infected' in cls.lower()
                     and 'not' not in cls.lower() else 0)
            for cls in class_names
        }
        print(f"  Class→Label mapping: {self.class_to_idx}")

        self.samples = []  # list of (img_path, label)
        self._load_samples()

    def _load_samples(self):
        exts = ['.jpg', '.jpeg', '.png', '.bmp']
        for cls in self.class_names:
            cls_dir = self.root_dir / cls
            label   = self.class_to_idx[cls]
            for ext in exts:
                for img_path in cls_dir.glob(f"*{ext}"):
                    self.samples.append((img_path, label))
        print(f"  Total samples loaded: {len(self.samples)}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert("RGB")
        if self.transform:
            image = self.transform(image)
        return image, torch.tensor(label, dtype=torch.float32)

    def get_labels(self):
        return [s[1] for s in self.samples]


# ── Instantiate datasets ──
print("📦 Loading Train Dataset:")
train_dataset = PCOSImageDataset(TRAIN_DIR, CLASS_NAMES, transform=train_transforms)

print("\n📦 Loading Test Dataset:")
test_dataset  = PCOSImageDataset(TEST_DIR,  CLASS_NAMES, transform=val_test_transforms)

# ── Split test → val + test ──
val_size  = int(0.5 * len(test_dataset))
test_size = len(test_dataset) - val_size

val_dataset, test_dataset_final = torch.utils.data.random_split(
    test_dataset,
    [val_size, test_size],
    generator=torch.Generator().manual_seed(SEED)
)

print(f"\n✅ Final Split:")
print(f"  Train : {len(train_dataset):>5} images")
print(f"  Val   : {len(val_dataset):>5} images")
print(f"  Test  : {len(test_dataset_final):>5} images")

# ── Verify one batch visually ──
sample_img, sample_label = train_dataset[0]
print(f"\n🖼️  Sample tensor shape : {sample_img.shape}")
print(f"   Label              : {int(sample_label)} "
      f"({'PCOS' if sample_label == 1 else 'Healthy'})")

BATCH_SIZE = 32

train_labels  = train_dataset.get_labels()
class_counts  = Counter(train_labels)
class_weights = {cls: 1.0 / count for cls, count in class_counts.items()}
sample_weights = [class_weights[lbl] for lbl in train_labels]

sampler = WeightedRandomSampler(
    weights     = torch.DoubleTensor(sample_weights),
    num_samples = len(sample_weights),
    replacement = True
)

# ── Loaders ──
train_loader = DataLoader(
    train_dataset,
    batch_size  = BATCH_SIZE,
    sampler     = sampler,
    num_workers = 2,
    pin_memory  = True
)

val_loader = DataLoader(
    val_dataset,
    batch_size  = BATCH_SIZE,
    shuffle     = False,
    num_workers = 2,
    pin_memory  = True
)

test_loader = DataLoader(
    test_dataset_final,
    batch_size  = BATCH_SIZE,
    shuffle     = False,
    num_workers = 2,
    pin_memory  = True
)

print(f"✅ DataLoaders ready")
print(f"  Train batches : {len(train_loader)}")
print(f"  Val batches   : {len(val_loader)}")
print(f"  Test batches  : {len(test_loader)}")
print(f"\n  Class 0 (Healthy) : {class_counts[0]}")
print(f"  Class 1 (PCOS)    : {class_counts[1]}")
print(f"  ✅ WeightedRandomSampler applied")

class ConvBlock(nn.Module):
    """
    Reusable Conv Block:
    Conv2D → BatchNorm → ReLU → (optional MaxPool)
    """
    def __init__(self, in_channels, out_channels,
                 kernel_size=3, pool=True):
        super().__init__()
        layers = [
            nn.Conv2d(in_channels, out_channels,
                      kernel_size=kernel_size,
                      padding=kernel_size // 2,
                      bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        ]
        if pool:
            layers.append(nn.MaxPool2d(kernel_size=2, stride=2))
        self.block = nn.Sequential(*layers)

    def forward(self, x):
        return self.block(x)


class PCOSConvNet(nn.Module):
    """
    Custom CNN for PCOS Ultrasound Image Classification.

    Architecture:
        Input (3×128×128)
        → ConvBlock(32)  → 32×64×64
        → ConvBlock(64)  → 64×32×32
        → ConvBlock(128) → 128×16×16
        → ConvBlock(256) → 256×8×8
        → ConvBlock(256) → 256×4×4
        → AdaptiveAvgPool → 256×1×1
        → FC(512) → Dropout → FC(256) → Dropout → FC(1) → Sigmoid
    """
    def __init__(self, in_channels=3, dropout_rate=0.4):
        super().__init__()

        self.features = nn.Sequential(
            ConvBlock(in_channels, 32,  pool=True),   # → 32×64×64
            ConvBlock(32,  64,  pool=True),            # → 64×32×32
            ConvBlock(64,  128, pool=True),            # → 128×16×16
            ConvBlock(128, 256, pool=True),            # → 256×8×8
            ConvBlock(256, 256, pool=True),            # → 256×4×4
        )

        self.global_avg_pool = nn.AdaptiveAvgPool2d((1, 1))  # → 256×1×1

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(inplace=True),
            nn.Dropout(p=dropout_rate),
            nn.Linear(512, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(inplace=True),
            nn.Dropout(p=dropout_rate / 2),
            nn.Linear(256, 1),
            nn.Sigmoid()
        )

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight,
                    mode='fan_out', nonlinearity='relu')
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
                nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.features(x)
        x = self.global_avg_pool(x)
        x = self.classifier(x)
        return x.squeeze(1)

    def count_parameters(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)


model_cnn = PCOSConvNet(in_channels=3, dropout_rate=0.4).to(DEVICE)

print("=" * 60)
print("🧠 PCOS CNN — Architecture Summary")
print("=" * 60)
print(model_cnn)
print("=" * 60)
print(f"📐 Input Shape      : 3 × {IMG_SIZE} × {IMG_SIZE}")
print(f"⚙️  Total Parameters: {model_cnn.count_parameters():,}")
print("=" * 60)

with torch.no_grad():
    dummy = torch.randn(2, 3, IMG_SIZE, IMG_SIZE).to(DEVICE)
    out   = model_cnn(dummy)
    print(f"\n✅ Sanity check passed!")
    print(f"   Input  : {dummy.shape}")
    print(f"   Output : {out.shape}  →  values: {out.cpu().numpy().round(4)}")

